<a href="https://colab.research.google.com/github/pratham-magar-13/PyTorch-Tutorial/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


#Introduction to Tensors
### Creating tensors
Pytorch tensors are created using torch.tensor()

In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#vector
vector=torch.tensor([7,7,9])
vector

tensor([7, 7, 9])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
# Matrix
matrix=torch.tensor([[7,8],
                   [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

#after braces there are two brackets, so its a 2 dimension

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# tensor
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

#after braces there are three brackets, so its a 3 dimension

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
tensor1=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]],
                      [[1,2,3],
                      [3,6,9],
                      [2,4,5]],
                      [[1,2,3],
                      [3,6,9],
                      [2,4,5]],
                      [[1,2,3],
                      [3,6,9],
                      [2,4,5]]])

In [ ]:
tensor1.ndim

3

In [ ]:
tensor1.shape

torch.Size([4, 3, 3])

In [ ]:
for objects in tensor1:
  print(objects)

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


# Random tensors
#### Why random tensors?
####RAndom tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [ ]:
# Create a random tensor of size(3,4)
RANDOM_TENSOR=torch.rand(3,4)
RANDOM_TENSOR

tensor([[0.8545, 0.4634, 0.5257, 0.7357],
        [0.2318, 0.3692, 0.3569, 0.3869],
        [0.6532, 0.4960, 0.6268, 0.0862]])

In [ ]:
RANDOM_TENSOR.ndim

2

In [ ]:
RANDOM_TENSOR1=torch.rand(10,4,5)
RANDOM_TENSOR1

tensor([[[0.2359, 0.8255, 0.2230, 0.6511, 0.4974],
         [0.4930, 0.2618, 0.9936, 0.8285, 0.7485],
         [0.6274, 0.2223, 0.6759, 0.0372, 0.8934],
         [0.7297, 0.0538, 0.5581, 0.4408, 0.7969]],

        [[0.9644, 0.6011, 0.8495, 0.6009, 0.8489],
         [0.5978, 0.2155, 0.2749, 0.7698, 0.0417],
         [0.8500, 0.4778, 0.2205, 0.4235, 0.3824],
         [0.8385, 0.6434, 0.8233, 0.2636, 0.7909]],

        [[0.8912, 0.9543, 0.3407, 0.0888, 0.9955],
         [0.5007, 0.8697, 0.9799, 0.6632, 0.3482],
         [0.2571, 0.6195, 0.6669, 0.7649, 0.2977],
         [0.5184, 0.6885, 0.4146, 0.9405, 0.1496]],

        [[0.1278, 0.9946, 0.2438, 0.4136, 0.3042],
         [0.2669, 0.0120, 0.1744, 0.2282, 0.8688],
         [0.7115, 0.5027, 0.3671, 0.6149, 0.7666],
         [0.0170, 0.1139, 0.8406, 0.5865, 0.8693]],

        [[0.7300, 0.5625, 0.2081, 0.0121, 0.6599],
         [0.2165, 0.7442, 0.8789, 0.8958, 0.5827],
         [0.1132, 0.2007, 0.9187, 0.0395, 0.3495],
         [0.4645, 0.843

# Getting information from tensors (tensors attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device


In [ ]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.7266, 0.9148, 0.5202, 0.2858],
        [0.0873, 0.9203, 0.7586, 0.1567],
        [0.3025, 0.4260, 0.0473, 0.1853]])

In [ ]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7266, 0.9148, 0.5202, 0.2858],
        [0.0873, 0.9203, 0.7586, 0.1567],
        [0.3025, 0.4260, 0.0473, 0.1853]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


#Manipulating tensors (tensor operation)

Tensor operations include:

* Addition
* Subtraction
* Multiplication(element wise)
* Division
* Matrix multiplication

In [ ]:
#create a tensor
tensor=torch.tensor([1,2,3])
tensor+10, tensor-10, tensor*10, tensor/10

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [ ]:
# Pytorch inbuilt functions
torch.mul(tensor,50)

tensor([ 50, 100, 150])

# Matrix Multiplication
Two main ways of performing multiplication in neural networks

In [ ]:
# Element wise multiplication
tensor=tensor*tensor

In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(98)

 # Condition for matrix multiplication
 m*n of one matrix and p*q of other matrix
 for it to work Inner dimension i.e n and q must be equal (n=q) and the result will be the outer dimension i,e m*q

In [ ]:
#shape for matrix multiplication
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensor_B=torch.tensor([[7,10],
                      [8,11],
                      [9,12]])

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# To fix our issues , we can manipulate the shape of one of our tensors using a **transpose**

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

# Finding the min, max, mean, sum, etc (**Tensor aggregation**)

In [ ]:
# Create a tensor
x=torch.arange(0,100,9)
x

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [ ]:
torch.max(x), torch.min(x)

(tensor(99), tensor(0))

In [ ]:
x = x.float()
print(f"Tensor x after converting to float: {x}")
print(f"Datatype of tensor x: {x.dtype}")
torch.mean(x), torch.sum(x)

Tensor x after converting to float: tensor([ 0.,  9., 18., 27., 36., 45., 54., 63., 72., 81., 90., 99.])
Datatype of tensor x: torch.float32


(tensor(49.5000), tensor(594.))

# Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes and input tensor to a defined shape
* View -  Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removies all '1' dimensions froma tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# lets create a tensor
x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked=torch.stack([x,x,x])
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# squeeze
x_stacked.shape
x_squeezed=torch.squeeze(x_stacked)
x_squeezed, x_squeezed.shape, x_squeezed.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([3, 9]),
 2)

In [ ]:
# unsqueeze
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
print(f"Previous dimension: {x_squeezed.ndim}")
x_unsqueezed=torch.unsqueeze(x_squeezed, dim=0)
print(f"new tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")
print(f"new dimension: {x_unsqueezed.ndim}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([3, 9])
Previous dimension: 2
new tensor: tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]])
new shape: torch.Size([1, 3, 9])
new dimension: 3


# Indexing (Selecting data from tensors)

Indexing with Pytorch is simlar to indexing with Numpy

In [ ]:
# Create a tensor
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [ ]:
# lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]
#first dimension first row

tensor([1, 2, 3])

In [ ]:
x[0,0,0]
#first dimension first row first column

tensor(1)

In [ ]:
x[0,1,1]
#first dimension second row second column

tensor(5)

In [ ]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

# Pytorch tensors and numpy
NumPy is a popular scientific Python numerical computing library.
Because of this, PyTorch has functionality to interact with it.

In [ ]:
#Numpy array to tensor
array=np.arange(1.0, 8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take random out of random)
To reduce the randomness in neural netwroks and PyTroch comes the concept of a **random seed**

In [ ]:
# create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.9959, 0.9225, 0.8991, 0.7600],
        [0.4049, 0.8470, 0.3587, 0.2797],
        [0.5586, 0.9392, 0.8070, 0.2111]])
tensor([[0.8450, 0.2439, 0.4295, 0.3291],
        [0.2665, 0.1180, 0.7376, 0.3745],
        [0.4268, 0.1332, 0.1277, 0.5104]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# lets make some random but reproducible tensors

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4
                           )
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

# manual seed only works for one block of code

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
